config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "top#index"
  resources :pets
  resources :users, only: [:show, :edit, :update]
  resources :reviews, only: [:new, :create]

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/scraping.rb
class Scraping
  def self.urls
    image_urls = []
    agent = Mechanize.new
    page = agent.get("https://www.min-breeder.com/dogSearch.php")

    breeds = page.search('.pic_kind_name')
    image_imgs = page.search('.pic_image img')
    image_imgs.each do |img|
      image_urls << img.get_attribute('src')
    end
    num = 0

    breeds.each do |breed|
      image_url = image_urls[num]
      br = breed.inner_text
      pet = Pet.new(breed: br, image_url: image_url)
      pet.save
      num = num + 1
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :pets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  before_action :move_to_index, except: [:index, :show]
  before_action :set_pet, only: [:show, :edit, :update]


  def index
    @pets = Pet.includes(:user).all.order('id DESC')
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.create(create_params)
  end

  def edit
  end

  def update
    if @pet.user_id == current_user.id
      @pet.update(update_params)
    end
  end

  def destroy
    pet = Pet.find(params[:id])
    if pet.user_id == current_user.id
      pet.destroy
    end
  end


  private

  def move_to_index
    redirect_to action: :index unless user_signed_in? && (current_user.seller_or_buyer == 1)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def create_params
    params.require(:pet).permit(:name, :breed, :birth_day, :image_url).merge(user_id: current_user.id)
  end

  def update_params
    params.require(:pet).permit(:name, :breed, :image_url)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
  end

  def new
  end

  def create
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @pets = Pet.includes(:user).order('id DESC').limit(9)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, :only => [:show]

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    current_user.update(update_params)
  end

  private
  def update_params
    params.require(:user).permit(:nickname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_header.html.erb
<% if user_signed_in? %>
  <div class='navbar navbar-default navbar-fixed-top'>
    <div class='container'>
      <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-responsive-collapse'>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to root_path, :class => 'navbar-brand' do %>
      <% end %>
      <div class='navbar-collapse collapse navbar-responsive-collapse navbar-right'>
        <ul class='nav navbar-nav'>
          <li><%= link_to 'HOME', root_path %></li>
          <li class='dropdown'>
            <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>アカウント <span class='caret'></span></a>
            <ul class='dropdown-menu' role='menu'>
              <li><%= link_to "マイページ", user_path(current_user) %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>

            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Famimal</title>
  <meta charset="utf-8">
  <meta name="author" content="pixelhint.com">
  <meta name="description" content="La casa free real state fully responsive html5/css3 home page website template"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0" />

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</head>
<body>
    <header>
      <div class="wrapper">
        <a href="/" class="logo">Famimal（ロゴ）</a>
        <a href="#" class="hamburger"></a>
        <nav>
          <ul>
            <li><a href="#">初めての方へ</a></li>
            <li><a href="/pets">子犬を探す</a></li>
            <li><a href="#">ブリーダーを探す</a></li>
          </ul>
          <% if user_signed_in? %>
          <a href="/users/sign_out" data-method="delete" class="login_btn">ログアウト</a>
          <a href="/users/<%= current_user.id %>" class="login_btn">マイページ</a>
          <% else %>
          <a href="/users/sign_in" class="login_btn">ログイン</a>
          <% end %>
        </nav>
      </div>
    </header><!--  end header section  -->



<%= yield %>

  <footer>
    <div class="wrapper footer">
      <ul>
        <li class="links">
          <ul>
            <li><a href="#">About</a></li>
            <li><a href="#">Support</a></li>
            <li><a href="#">Terms</a></li>
            <li><a href="#">Policy</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </li>

        <li class="links">
          <ul>
            <li><a href="#">Appartements</a></li>
            <li><a href="#">Houses</a></li>
            <li><a href="#">Villas</a></li>
            <li><a href="#">Mansions</a></li>
            <li><a href="#">...</a></li>
          </ul>
        </li>

        <li class="links">
          <ul>
            <li><a href="#">New York</a></li>
            <li><a href="#">Los Anglos</a></li>
            <li><a href="#">Miami</a></li>
            <li><a href="#">Washington</a></li>
            <li><a href="#">...</a></li>
          </ul>
        </li>

        <li class="about">
          <p>La Casa is real estate minimal html5 website template, designed and coded by pixelhint, tellus varius, dictum erat vel, maximus tellus. Sed vitae auctor ipsum</p>
          <ul>
            <li><a href="http://facebook.com/pixelhint" class="facebook" target="_blank"></a></li>
            <li><a href="http://twitter.com/pixelhint" class="twitter" target="_blank"></a></li>
            <li><a href="http://plus.google.com/+Pixelhint" class="google" target="_blank"></a></li>
            <li><a href="#" class="skype"></a></li>
          </ul>
        </li>
      </ul>
    </div>

    <div class="copyrights wrapper">
      Copyright © 2015 <a href="http://pixelhint.com" target="_blank" class="ph_link" title="Download more free Templates">Pixelhint.com</a>. All Rights Reserved.
    </div>
  </footer><!--  end footer  -->
  
</body>
</html>

app/views/pets/create.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>子犬の掲載が完了しました。</h3>
    <%= link_to "ホームに戻る", root_path %>
  </div>
</div>

app/views/pets/destroy.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>子犬情報を削除しました。</h3>
    <%= link_to "ホームに戻る", root_path %>
  </div>
</div>

app/views/pets/edit.html.erb
<div class="row form">
  <div class="col-lg-12">
    <%= form_for (@pet) do |f| %>
      <h2>登録情報の編集</h2>
      <div class="form-group">
        <div class="col-lg-6">
          <%= f.text_field :name, placeholder: "名前", class: "form-control" %>
          <%= f.text_field :breed, placeholder: "犬種", class: "form-control" %>
          <%= f.text_field :image_url, placeholder: "画像", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "送信", class: "btn btn-primary withripple" %>
      </div>
    <% end %>
  </div>
</div>

<h2>この子犬情報を掲載から削除する</h2>

<div class="profile_edit">
  <%= link_to "削除する", "/pets/#{@pet.id}", {:method => :delete, :class => "btn btn-primary withripple" } %>
</div>

app/views/pets/index.html.erb
<section class="listings">
  <div class="wrapper">
    <ul class="properties_list">
      <% @pets.each do |pet| %>
      <li>
        <a href="pets/<%= pet.id %>">
          <img src="<%= pet.image_url %>" alt="" title="" class="property_img"/>
        </a>
        <span class="price"><%= pet.price %>円</span>
        <div class="property_details">
          <h1>
            <a href="#"><%= pet.breed %></a>
          </h1>
          <h2>生年月日:</span></h2>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</section>  <!--  end listing section  -->

app/views/pets/new.html.erb
<div class="row form">
  <div class="col-lg-12">
    <%= form_for(@pet) do |f| %>
      <h2></h2>
      <div class="form-group">
        <div class="col-lg-6">
          <%= f.text_field :name, placeholder: "名前", class: "form-control" %>
          <%= f.text_field :breed, placeholder: "犬種", class: "form-control" %>
          <%= f.text_field :birth_day, placeholder: "誕生日（xxxx/xx/xx）", class: "form-control" %>
          <%= f.text_field :image_url, placeholder: "画像", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "送信", class: "btn btn-primary withripple" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pets/show.html.erb
<div class="h5">
<h1><%= @pet.breed %>の子犬詳細　子犬ID：<%= @pet.id %></h1>
</div>

  <% if user_signed_in? %>
  <% if current_user.id == @pet.user_id %>
    <div class="profile_edit">
      <%= link_to "子犬の情報編集", edit_pet_path(@pet.id), {:class => "btn btn-primary withripple" }%>
    </div>
  <% end %>
  <% end %>

<div style="text-align:center;padding-top:10px;">
<div id="detailInq">

<p>
<a href='https://www.min-breeder.com/dogInquiry.php?dog_id=1610-01361' class="detail_inq_btn dog_inq">この子犬の見学/購入希望・お問い合わせ（無料）</a>
</p>

</div>
</div>

<div class="dog_list">
<div style="float:left">子犬ID ： <%= @pet.id %></div>
<div style="float:right">掲載日：●</div>
<div class="clearfix"></div>


<table style="width:100%; margin:6px 0px 0px 0px;">
<tr>
<th>犬種<br><img src="https://d2vg66dbzxkile.cloudfront.net/images/dummy.gif" width="103" height="1"></th>
<td colspan="3" style="width:576px;">
<%= @pet.breed %>


</td>
</tr>
<tr>
<th>性別</th>
<td style="width:240px; border-right:none;">●<br></td>
<th>誕生日<br><img src="https://d2vg66dbzxkile.cloudfront.net/images/dummy.gif" width="96" height="1"></th>
<td style="width:240px;">
<%= @pet.birth_day %>（今日で生後<b>●</b>日）<br>

</td>
</tr>
<tr>
<th>地域</th>
<td style="width:240px; border-right:none; vertical-align:middle;">●<br /></td>
<th>毛色</th>
<td style="width:240px;">●<br /></td>
</tr>
<tr>
<th>価格</th>
<td style="width:240px; border-right:none;"><font style="font-weight:bold;" color="red"><%= @pet.price %></font> 円（税込）</td>
<th>状況</th>
<td style="width:240px;">
販売中
<br />
</td>
</tr>
<tr>
<th>アピールポイント</th>
<td colspan="3" style="width:576px;">●<br /></td>
</tr>


</table>





<div>
<img src='<%= @pet.image_url %>' border='0' class='property_img' style="max-height:728px; width:auto;">
</div>

<div id="detail_img_comment" style="margin-top:8px;">●（コメント）</div>
</div>


<br clear="both">

<div class="dog_comment_title">
ブリーダーからの子犬紹介文
</div>
<div class="dog_comment">●<br />
<br />
</div>

app/views/pets/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>子犬情報の編集が完了しました。</h3>
    <%= link_to "ホームに戻る", root_path %>
  </div>
</div>

app/views/top/index.html.erb
  <section class="hero">
      <section class="caption">
        <h2 class="caption">Find Your Famimal</h2>
        <h3 class="properties">dogs - cats</h3>
      </section>
  </section><!--  end hero section  -->

  <section class="search">
    <div class="wrapper">
      <form action="#" method="post">
        <input type="text" id="search" name="search" placeholder="What are you looking for?"  autocomplete="off"/>
        <input type="submit" id="submit_search" name="submit_search"/>
      </form>
      <a href="#" class="advanced_search_icon" id="advanced_search_btn"></a>
    </div>

    <div class="advanced_search">
      <div class="wrapper">
        <span class="arrow"></span>
        <form action="#" method="post">
          <div class="search_fields">
            <input type="text" class="float" id="check_in_date" name="check_in_date" placeholder="Check In Date"  autocomplete="off">

            <hr class="field_sep float"/>

            <input type="text" class="float" id="check_out_date" name="check_out_date" placeholder="Check Out Date"  autocomplete="off">
          </div>
          <div class="search_fields">
            <input type="text" class="float" id="min_price" name="min_price" placeholder="Min. Price"  autocomplete="off">

            <hr class="field_sep float"/>

            <input type="text" class="float" id="max_price" name="max_price" placeholder="Max. price"  autocomplete="off">
          </div>
          <input type="text" id="keywords" name="keywords" placeholder="Keywords"  autocomplete="off">
          <input type="submit" id="submit_search" name="submit_search"/>
        </form>
      </div>
    </div><!--  end advanced search section  -->
  </section><!--  end search section  -->


  <section class="listings">
    <div class="wrapper">
      <ul class="properties_list">
        <% @pets.each do |pet| %>
        <li>
          <a href="pets/<%= pet.id %>">
            <img src="<%= pet.image_url %>" alt="" title="" class="property_img"/>
          </a>
          <span class="price"><%= pet.price %>円</span>
          <div class="property_details">
            <h1>
              <a href="#"><%= pet.breed %></a>
            </h1>
            <h2>生年月日:</span></h2>
          </div>
        </li>
        <% end %>
      </ul>
      <div class="more_listing">
        <a href="/pets" class="more_listing_btn">View More Listings</a>
      </div>
    </div>
  </section>  <!--  end listing section  -->

app/views/users/edit.html.erb
<div class="row form">
  <div class="col-lg-12">
    <%= form_for (current_user) do |f| %>
      <h2>登録情報</h2>
      <div class="form-group">
        <div class="col-lg-6">
          <%= f.text_field :nickname, placeholder: "ニックネーム", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "送信", class: "btn btn-primary withripple" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.nickname %>さんのユーザーページです。

  <% if current_user.id == @user.id %>
    <div class="profile_edit">
      <%= link_to "プロフィール編集", edit_user_path(current_user), {:class => "btn btn-primary withripple" }%>
      <% if current_user.seller_or_buyer == 1 %>
      <%= link_to "子犬を掲載する", new_pet_path, :class => "btn btn-primary withripple" %>
      <% end %>
    </div>
  <% end %>

app/views/users/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>プロフィールの編集が完了しました。</h3>
    <%= link_to "ホームに戻る", root_path %>
  </div>
</div>